version: '1.0.2-ci.{build}'
init:
  - git config --global core.autocrlf input
branches:
  only:
    - master
build_script:
  - build.cmd
clone_depth: 1
test: off
artifacts:
  - path: 'artifacts\*.nupkg'
    name: Sleet.nupkg

  - path: 'artifacts\Sleet.exe'
    name: Sleet.exe

  - path: 'artifacts\*.tar.bz2'
    name: Sleet.tar