init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
build_script:
  - build.cmd
clone_depth: 1
test: off
deploy: off
cache:
  - '%USERPROFILE%\.nuget\packages'
