init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
build_script:
  - build.cmd
clone_depth: 1
test: off
cache:
  - '%USERPROFILE%\.nuget\packages'
artifacts:
  - path: 'artifacts\*.nupkg'
deploy:
  provider: NuGet
  server: https://www.myget.org/F/sleet/api/v2/package
  api_key:
    secure: xap/w8Pi8ZkgpAwE0ofkKjtO8NTzeK0Gwm4LUPwRb+crbXkLInOfoapPE/fZXHvz
  skip_symbols: false
  symbol_server: https://www.myget.org/F/sleet/symbols/api/v2/package
  artifact: /.*\.nupkg/
  on:
    branch: master